# Generated by Django 3.2.13 on 2023-02-16 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230216_1314'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailVerifications',
            new_name='EmailVerification',
        ),
    ]
